FROM mcr.microsoft.com/devcontainers/cpp:1-debian-11


RUN \
  apt-get update && export DEBIAN_FRONTEND=noninteractive\
  apt-get -y install --no-install-recommends g++ cmake ninja-build libsdl2-dev libpng-dev libjpeg-dev libgl1-mesa-dev libglew-dev libopenal-dev libmad0-dev uuid-dev 


